version: "3.7"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-thisisecndbpassword}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  nginx:
    restart: always
    image: nginx
    container_name: api_nginx
    ports:
      - '1000:80'
      - '443:443'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DOMAIN: ${DOMAIN}
      WEB_API_PORT: ${WEB_API_PORT}
    volumes:
      - ./nginx/default.test.conf:/etc/nginx/conf.d/default.test.conf.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.test.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERT_EMAIL} --agree-tos --no-eff-email --force-renewal --staging -d ${DOMAIN}
    # command: certonly --webroot --webroot-path=/var/www/certbot --email email --agree-tos --no-eff-email --force-renewal -d example.com www.example.com

  web_api:
    build:
        dockerfile: Dockerfile.web-api.prod
        context: ./
    container_name: web_api_nest
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules 
      - /app/packages/ecn-discord-bot/node_modules
      - /app/packages/ecn-eip712vc/node_modules
      - /app/packages/ecn-prisma/node_modules
      - /app/packages/ecn-sbt-api/node_modules
      - /app/packages/ecn-sbt-contract/node_modules
      - /app/packages/ecn-web-api/node_modules
      - /app/packages/ecn-web-frontend/node_modules
    

  redis:
    image: redis
    container_name: tutorial_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - redisdata:/data
    ports:
      - 6379:6379

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redisdata:
  web-root:
  certbot-etc:
  certbot-var:
  dhparam:
  # pgadmin:
